import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";


import "./globals.css";

const playfair = Playfair_Display({  subsets: ["latin"], weight: "400"});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth [&::-webkit-scrollbar]:hidden">
      <body className={playfair.className}>{children}</body>
    </html>
  );
}
